maxParsingInterval: 600
minParsingInterval: 300
maxpageNavigationInterval: 10
minpageNavigationInterval: 5
telegramToken: 565399062:AAHd-_CapBje_0Bq6sa_CGoLOYC8RcFDJVM
mongoDBCluster: HouseFinderCluster
mongoDBUser: housefinder
mongoDBPass: byZLg7sv5cQFVUlr
mongoDbDatabase: housefinder
mongoDbCollection: links
userId:
- 123456
websites:
  immobiliare:
    url: https://www.immobiliare.it/affitto-case/bologna/?criterio=dataModifica&ordine=desc&prezzoMinimo=minPrice&prezzoMassimo=maxPrice&superficieMinima=60&localiMinimo=roomNumber&idMZona[]=17&idMZona[]=23&idMZona[]=31
    maxPrice: 900
    minPrice: 200
    roomNumber: 3
  subito:
    url: https://www.subito.it/annunci-emilia-romagna/affitto/appartamenti/bologna/bologna/?ps=minPrice&pe=maxPrice&rs=roomNumber
    maxPrice: 900
    minPrice: 200
    roomNumber: 3
  casa:
    url: https://www.casa.it/srp/?tr=affitti&numRoomsMin=roomNumber&priceMin=minPrice&priceMax=maxPrice&propertyTypeGroup=case&q=12d65861%2C171c3cab%2C035cb1f0%2C853e62a4%2Cd2a360ef%2Cd80cd525
    maxPrice: 900
    minPrice: 200
    roomNumber: 3
  idealista:
    url: https://www.idealista.it/affitto-case/bologna-bologna/con-prezzo_maxPrice,prezzo-min_minPrice,trilocali-3,quadrilocali-4,5-locali-o-piu/?ordine=pubblicazione-desc
    maxPrice: 900
    minPrice: 200
    roomNumber: 3